### ISSUE TITLE
Crash on invalid url

### ISSUE THREAD

**Issue by Jackymancs4** [styfle/links-awakening#25]
Hello,
the line https://github.com/styfle/links-awakening/blob/400fd6f4c8f7c7c31a01ff27c5c12e923e4f493a/src/index.ts#L77 (and https://github.com/styfle/links-awakening/blob/400fd6f4c8f7c7c31a01ff27c5c12e923e4f493a/src/index.ts#L73) assumes that href is a well formatted URL, which is not necessarily the case.

I have encountered links like `http://tel:04993195xx` which crashes the program.
An AwakenResult should be returned instead, with a message like 'Invalid URL'.

```
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:399:5)
    at URL.onParseError (node:internal/url:565:9)
    at new URL (node:internal/url:645:5)
    at Object.onopentag (file:///Users/jack/.nvm/versions/node/v18.14.0/lib/node_modules/links-awakening/dist/index.js:50:35)
    at Parser.endOpenTag (file:///Users/jack/.nvm/versions/node/v18.14.0/lib/node_modules/links-awakening/node_modules/htmlparser2/lib/esm/Parser.js:193:86)
    at Parser.onopentagend (file:///Users/jack/.nvm/versions/node/v18.14.0/lib/node_modules/links-awakening/node_modules/htmlparser2/lib/esm/Parser.js:204:14)
    at Tokenizer.stateBeforeAttributeName (file:///Users/jack/.nvm/versions/node/v18.14.0/lib/node_modules/links-awakening/node_modules/htmlparser2/lib/esm/Tokenizer.js:404:22)
    at Tokenizer.parse (file:///Users/jack/.nvm/versions/node/v18.14.0/lib/node_modules/links-awakening/node_modules/htmlparser2/lib/esm/Tokenizer.js:763:22)
    at Tokenizer.write (file:///Users/jack/.nvm/versions/node/v18.14.0/lib/node_modules/links-awakening/node_modules/htmlparser2/lib/esm/Tokenizer.js:154:14)
    at Parser.write (file:///Users/jack/.nvm/versions/node/v18.14.0/lib/node_modules/links-awakening/node_modules/htmlparser2/lib/esm/Parser.js:432:28) {
  input: 'http://tel:04993195xx',
  code: 'ERR_INVALID_URL'
}

Node.js v18.14.0
```

**Comment by styfle** [comment]
Thanks for reporting this bug!

It will be fixed in PR #26
